version: "3"
services:
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:latest
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:latest
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:latest
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:latest
